spring:
  application:
    name: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1  # 指定该Eureka实例的主机名
#    ip-address: 192.168.1.1
#    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:8862/eureka/
#  server:
#    enable-self-preservation: false

